import { createSlice } from "@reduxjs/toolkit";
const filterProductsSlice = createSlice({
  name: "filterProductsSlice",
  initialState: [
    {
        id: 25,
      image: "/p1.webp",
      title: "Lorem ipsum dolor sit amet",
      price: 89.99,
      oldPrice: 129.99,
      rating: 5,
      reviews: 24,
      category: "Clothing",
      badge: "Sale",
    },

    {
        id: 26,
      image: "/p1.webp",
      title: "Consectetur adipiscing elit",
      price: 249.99,
      rating: 4,
      reviews: 18,
      category: "Accessories",
      badge: " ",
    },
    {
        id: 27,
      image: "/p1.webp",
      title: "Sed do eiusmod tempor",
      price: 59.99,
      rating: 3,
      reviews: 7,
      category: "Accessories",
      badge: "New",
    },
    {
        id: 28,
      image: "/p1.webp",
      title: "Incididunt ut labore et dolore",
      price: 79.99,
      oldPrice: 99.99,
      rating: 5,
      reviews: 32,
      category: "Electronics",
    },
    {
        id: 29,
      image: "/p1.webp",
      title: "Incididunt ut labore et dolore",
      price: 79.99,
      oldPrice: 99.99,
      rating: 5,
      reviews: 32,
      category: "Clothing",
    },
    {
        id:30,
      image: "/p1.webp",
      title: "Incididunt ut labore et dolore",
      price: 79.99,
      oldPrice: 99.99,
      rating: 5,
      reviews: 32,
      category: "Electronics",
    },
    {
        id:31,
      image: "/p1.webp",
      title: "Incididunt ut labore et dolore",
      price: 79.99,
      oldPrice: 99.99,
      rating: 5,
      reviews: 32,
      category: "Clothing",
    },
    {
        id:32,
      image: "/p1.webp",
      title: "Incididunt ut labore et dolore",
      price: 79.99,
      oldPrice: 99.99,
      rating: 5,
      reviews: 32,
      category: "Electronics",
    },
  ],
  reducers: {},
});
export default filterProductsSlice.reducer
